# fly.toml app configuration file generated for tinel-server on 2023-07-31T19:44:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tinel-server"
primary_region = "sin"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
